export const allRecipes = [
  {
    id: 'spicy-lentil-soup',
    title: 'Spicy Vegan Lentil Soup',
    image: require('../../assets/recipes1.webp'),
    type: 'vegan',
    time: '<30 min',
    servings: 4,
    origin: { country: 'India', flag: '🇮🇳' },
    description:
      'This comforting vegan lentil soup is loaded with warming Indian-inspired spices, hearty vegetables, and fresh greens. It’s protein-packed, creamy without any dairy, and perfect for quick weeknight dinners or meal prep.',
    steps: [
      'Heat olive oil in a large pot over medium heat. Add chopped onion and carrots, and cook until softened (about 5 minutes).',
      'Add minced garlic, cumin, curry powder, and thyme. Cook for 30 seconds until fragrant.',
      'Add diced tomatoes and stir occasionally for a few minutes.',
      'Add lentils, vegetable broth, water, salt, red pepper flakes, and black pepper. Stir to combine.',
      'Bring to a boil, then reduce heat and simmer uncovered for 25–30 minutes until lentils are tender.',
      'Use an immersion blender to purée part of the soup for a creamier texture (or blend a few cups separately and return to pot).',
      'Stir in chopped collard greens or kale, and cook for 5 minutes until tender.',
      'Remove from heat and stir in lemon juice. Adjust seasonings to taste before serving.',
    ],
  },
  {
    id: 'grilled-salmon-bowl',
    title: 'Grilled Salmon Bowl',
    image: require('../../assets/recipes2.jpg'),
    type: 'pescetarian',
    time: '~1 hour',
    servings: 2,
    origin: { country: 'USA', flag: '🇺🇸' },
    description:
    'A quick, healthy, and flavorful salmon bowl featuring teriyaki-glazed salmon served over jasmine rice, topped with fresh avocado, cucumber, mango, edamame, and drizzled with sriracha mayo. Perfect for a nutritious weeknight meal.',
    steps: [
    'Prepare the teriyaki sauce by combining all sauce ingredients in a saucepan over medium heat. Bring to a boil, stirring constantly, and boil for about 1 minute until the sauce thickens. Allow to cool.',
    'Marinate the salmon fillets by pouring ¼ cup of the prepared teriyaki sauce over them. Let them marinate for at least 20 minutes or up to overnight.',
    'Cook jasmine rice according to package instructions.',
    'Preheat the air fryer to 400ºF. Spray the basket with non-stick spray and place the marinated salmon fillets inside. Air fry for about 5-7 minutes, or until the salmon is cooked through and flakes easily with a fork.',
    'Assemble the bowls by dividing the cooked rice among serving bowls. Top each with a piece of teriyaki salmon, sliced avocado, diced mango, sliced cucumber, and edamame.',
    'Drizzle additional teriyaki sauce and sriracha mayo over the top. Garnish with chopped green onions and cilantro before serving.',
  ],
  },
  {
    id: 'pad-thai',
    title: 'Vegetarian Pad Thai',
    image: require('../../assets/recipes3.jpg'),
    type: 'vegetarian',
    time: '~1 hour',
    servings: 3,
    origin: { country: 'Thailand', flag: '🇹🇭' },
    description:
      'A vibrant and satisfying vegetarian Pad Thai that captures the authentic flavors of Thailand. This plant-based version omits fish sauce and shrimp, offering a delicious alternative with tofu, rice noodles, and a tangy-sweet sauce.',
    steps: [
      'Soak rice noodles in hot water for about 10 minutes until softened. Drain and set aside.',
      'Prepare tofu by baking, air frying, or pan frying until golden and crispy. Set aside.',
      'Heat oil in a large skillet or wok over medium heat. Add minced garlic and sauté until fragrant.',
      'Add sliced red and yellow bell peppers to the skillet and cook until slightly tender.',
      'Push the vegetables to one side of the skillet and pour in whisked eggs (if using). Scramble the eggs until cooked through, then mix with the vegetables.',
      'Add the soaked noodles to the skillet along with the prepared Pad Thai sauce. Toss everything together to combine.',
      'Gently fold in the cooked tofu and bean sprouts, mixing until evenly distributed and heated through.',
      'Garnish with chopped scallions, roasted peanuts, and fresh cilantro. Serve with lime wedges on the side.',
    ],
  },
  {
    id: 'chickpea-curry',
    title: 'Chickpea Curry',
    image: require('../../assets/recipes4.jpg'),
    type: 'vegan',
    time: '>1 hour',
    servings: 6,
    origin: { country: 'India', flag: '🇮🇳' },
    description:
      'A quick and flavorful vegan chickpea curry inspired by Indian chana masala. This one-pot dish combines pantry staples like chickpeas and tomatoes with aromatic spices, creating a rich and satisfying meal perfect for busy weeknights.',
    steps: [
      'Heat oil in a large skillet over medium heat. Add chopped onions and cook until golden brown.',
      'Stir in minced garlic and cook for another minute until fragrant.',
      'Add curry powder and ground cumin, stirring to coat the onions and garlic with the spices.',
      'Pour in crushed tomatoes and cook for a few minutes to blend the flavors.',
      'Add drained chickpeas and coconut milk to the skillet, stirring to combine.',
      'Simmer the curry for 15-20 minutes, allowing the sauce to thicken and the flavors to meld.',
      'Season with salt and pepper to taste.',
      'Serve hot over rice or with naan bread, garnished with fresh cilantro if desired.',
    ],
  },
  {
    id: 'shrimp-tacos',
    title: 'Shrimp Tacos',
    image: require('../../assets/recipes5.jpg'),
    type: 'pescetarian',
    time: '<30 min',
    servings: 2,
    origin: { country: 'USA', flag: '🇺🇸' },
    description:
      'These easy shrimp tacos are the perfect simple dinner for busy weeknights! Plump, juicy shrimp are cooked in a flavorful spice blend then wrapped in warm flour tortillas and piled high with your favorite toppings.',
    steps: [
      'Thaw and peel the shrimp. If using frozen shrimp, run them under cool water until thawed. Then peel them and remove the tails.',
      'Prepare your desired toppings, such as sliced avocado, sour cream, salsa, shredded cabbage, pico de gallo, red onions, and fresh cilantro.',
      'In a skillet, add the shrimp along with olive oil, garlic powder, onion powder, smoked paprika, ground cumin, and chili powder. Cook over medium-high heat until the shrimp are pink, flipping or stirring occasionally (about 5-6 minutes).',
      'Warm the flour tortillas.',
      'Assemble the tacos by placing the cooked shrimp into the warm tortillas and adding your prepared toppings.',
      'Serve immediately and enjoy!',
    ],
  },
  {
    id: 'stuffed-peppers',
    title: 'Stuffed Peppers',
    image: require('../../assets/recipes6.jpg'),
    type: 'vegetarian',
    time: '>1 hour',
    servings: 4,
    origin: { country: 'Italy', flag: '🇮🇹' },
    description:
      'These vegetarian stuffed peppers are a hearty and flavorful meal, filled with a zesty mix of brown rice, black beans, corn, and spices, then topped with melty cheese. Perfect for a comforting and nutritious dinner.',
    steps: [
      'Preheat the oven to 450°F (230°C). Slice the bell peppers in half lengthwise and remove the seeds and membranes.',
      'Place the pepper halves cut-side up on a baking sheet. Drizzle with olive oil and sprinkle with salt and pepper.',
      'Roast the peppers in the preheated oven for 10 minutes until they begin to soften. Remove and set aside.',
      'In a large skillet, heat olive oil over medium heat. Add chopped onion and jalapeño; sauté until softened.',
      'Stir in minced garlic, tomato paste, chili powder, cumin, salt, and pepper. Cook for 2-3 minutes until fragrant.',
      'Add cooked brown rice, black beans, and corn to the skillet. Mix well to combine all ingredients.',
      'Remove the skillet from heat and stir in lime juice and zest. Adjust seasoning to taste.',
      'Fill each roasted pepper half with the rice and bean mixture. Top with shredded cheese.',
      'Return the stuffed peppers to the oven and broil for 5-10 minutes until the cheese is melted and bubbly.',
      'Garnish with chopped fresh cilantro and serve warm.',
    ],
  },
  {
    id: 'zucchini-noodles',
    title: 'Zucchini Noodles with Pesto',
    image: require('../../assets/recipes7.jpg'),
    type: 'gluten-free',
    time: '<30 min',
    servings: 1,
    origin: { country: 'Italy', flag: '🇮🇹' },
    description:
      'Fresh zucchini noodles tossed with a vibrant basil and pumpkin seed pesto, complemented by juicy cherry tomatoes. A light, healthy, and flavorful dish perfect for summer meals.',
    steps: [
      'Prepare the pesto: In a food processor, combine roughly chopped onion, garlic, fresh basil leaves, toasted pepitas, olive oil, red wine vinegar (or lemon juice), and a pinch of red pepper flakes. Blend until smooth and season with salt to taste.',
      'Spiralize the zucchini into noodles using a spiralizer or julienne peeler. Place the zucchini noodles in a large bowl and sprinkle with a little salt. Let them sit for 10 minutes to release excess moisture, then gently squeeze out the liquid.',
      'Halve the cherry tomatoes vertically.',
      'In a large bowl, toss the zucchini noodles with the prepared pesto until well coated.',
      'Add the halved cherry tomatoes and gently mix to combine.',
      'Garnish with fresh basil leaves and serve immediately.',
    ],
  },
  {
    id: 'quinoa-salad',
    title: 'Quinoa Salad Bowl',
    image: require('../../assets/recipes8.jpg'),
    type: 'gluten-free',
    time: '<30 min',
    servings: 2,
    origin: { country: 'Greece', flag: '🇬🇷' },
    description:
      'A vibrant and healthy Mediterranean-inspired quinoa bowl, featuring fresh cucumbers, tomatoes, red onion, and feta cheese, all drizzled with a creamy homemade tzatziki sauce. Perfect for a light lunch or dinner.',
    steps: [
      'Cook quinoa: Rinse 1 cup of quinoa under cold water. In a saucepan, combine the quinoa with 2 cups of water. Bring to a boil, then reduce heat to low, cover, and simmer for 15-20 minutes until the quinoa is tender and water is absorbed. Fluff with a fork and set aside to cool.',
      'Prepare vegetables: While the quinoa is cooking, slice 1 cup of grape or cherry tomatoes in half, dice 1/4 cup of red onion, and slice 1 cup of cucumber into quarters.',
      'Make tzatziki sauce: Grate 1/2 cucumber and squeeze out excess moisture. In a bowl, combine the grated cucumber with 1 cup of plain Greek yogurt, 2 minced garlic cloves, 2 tablespoons of lemon juice, 2 teaspoons of chopped fresh dill, and a pinch of salt and pepper. Mix well and set aside.',
      'Assemble the bowl: Divide the cooked quinoa between two bowls. Top each with the prepared cucumbers, tomatoes, red onion, and 1/4 cup of crumbled feta cheese.',
      'Drizzle each bowl with a generous amount of the homemade tzatziki sauce.',
      'Serve immediately, or refrigerate components separately for meal prep and assemble when ready to eat.',
    ],
  },
  {
    id: 'chocolate-avocado-mousse',
    title: 'Chocolate Avocado Mousse',
    image: require('../../assets/recipes9.jpg'),
    type: 'dessert',
    time: '<30 min',
    servings: 3,
    origin: { country: 'Mexico', flag: '🇲🇽' },
    description:
      'A rich, creamy chocolate mousse made without heavy cream or eggs. This healthier dessert uses ripe avocados for a smooth texture and is naturally vegan and gluten-free.',
    steps: [
      'Add 2 ripe avocados, ¼ cup coconut milk, 2 tablespoons cocoa powder, 4 tablespoons maple syrup, ½ teaspoon vanilla extract, and a pinch of salt to a food processor.',
      'Blend until the mixture is smooth and creamy, ensuring no avocado chunks remain.',
      'Divide the mousse evenly into 4 serving bowls.',
      'Refrigerate the bowls for at least 30 minutes to allow the flavors to meld and the mousse to set.',
      'Before serving, top each bowl with fresh mint leaves and raspberries for garnish.',
    ],
  },
  {
    id: 'rice-flour-banana-pancakes',
    title: 'Rice Flour Banana Pancakes',
    image: require('../../assets/recipes10.jpg'),
    type: 'gluten-free',
    time: '~1 hour',
    servings: 4,
    origin: { country: 'Indonesia', flag: '🇮🇩' },
    description:
      'Fluffy and light banana pancakes made with stone-milled rice flour. These gluten-free treats are inspired by Southeast Asian flavors and are perfect for a wholesome breakfast or brunch.',
    steps: [
      'In a mixing bowl, beat 3 eggs.',
      'Stir in 125ml of milk, 1 tablespoon of vegetable oil, 1 tablespoon of sugar, and ½ tablespoon of salt.',
      'Whisk in 125g of rice flour until the batter is smooth and free of lumps.',
      'Gently fold in 50g of dried banana slices.',
      'Cover the bowl and let the batter rest at room temperature for 1 hour.',
      'Heat a lightly-oiled griddle over medium-high heat.',
      'Drop large spoonfuls of batter onto the griddle.',
      'Cook until bubbles form and the edges appear dry.',
      'Flip the pancakes and cook until the other side is golden brown.',
      'Repeat with the remaining batter and serve warm.',
    ],
  },
];
